name: Deploy

on:
  workflow_dispatch:
    inputs:
      server-host:
        description: 'Server Host'
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name:  Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate ECR Password
        id: ecr-password
        run: |
          TOKEN=$(aws ecr get-login-password --region ${{ secrets.AWS_REGION }})
          echo "::add-mask::$TOKEN"
          echo "docker_token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dio-postgres-app-repo
          IMAGE_TAG: ${{ github.sha }}
          ECR_PASSWORD: ${{ steps.ecr-password.outputs.docker_token }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dio-postgres-app-repo
          IMAGE_TAG: ${{ github.sha }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_PASSWORD: ${{ steps.ecr-password.outputs.docker_token }}
        with:
            host: ${{ inputs.server-host }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            port: 22
            debug: true
            timeout: 30s
            envs: ECR_REGISTRY,ECR_REPOSITORY,IMAGE_TAG,ECR_PASSWORD
            script: |
              # Login to ECR on the server
              echo $ECR_PASSWORD | docker login --username AWS --password-stdin $ECR_REGISTRY
              
              # Pull the new image
              docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
              
              # Remove container antigo se existir
              if [ "$(docker ps -a -q -f name=app-container)" ]; then
                docker stop app-container
                docker rm app-container
              fi
              
              # Run the new container
              docker run -d \
                --name app-container \
                -p 8080:8080 \
                $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG